### ISSUE TITLE
Lockjaw swamp

### ISSUE THREAD

**Issue by Spinyspino8** [RicardoTheCoder/ViktorsDiskoveries#10]
**What will this feature do?**

this is an idea I have had for this mod for the longest time. the lockjaw swamp should be a new location on the new continent of sora, the lockjaw swamp is your typical looking mossy, viney, muddy swamp but with one big difference.

Lockjaw slimes!

the lockjaw slimes would add an interesting dynamic to the gameplay of viktors diskoveries because the lockjaws are mean little munchers! the lockjaws have a nearly identical size and body to pink slimes except they are a deep brown. (think hunter but darker to blend with the swamp) the thing that sets them apart is the big metal grill on its face which increases the bite force allowing the lockjaw a vicious bite and giving it the name. the swamp would also be home to many other predatory slimes such as hunters, and Tarr. the lockjaws preferred food is the new metal resource! the digestive tract of the lockjaw is almost as aggressive as the slime itself! the metal it chews up is then used as a nutrient stand-in (kind of like how some birds eat bones) and that makes their grill stronger! (it doesn't have to increase the damage, its just a way of an in-lore explanation to the metal chewing) the metal itself is found in the sides of the mossy floor as the swamp itself has adapted to the lockjaws and now produces a metal-like substance for the slimes. while metal may be their faviroute food its not their only food source. the lockjaws can also eat berries but they are not as yummy as the raw metal they grind up!

**How it should integrate into the mod? (Optional)**

the swamp integrates by being a location in the new continent and by also being the only place you can find natural lockjaw slimes!

P.S love what you are doing ricardo! even if this idea doesn't exactly suit the mod to your needs I will still be here supporting this mod all day long. I have not been this excited for slime rancher since possibly the release and this is just so damn awesome!

**Comment by RicardoTheCoder** [comment]
The idea seems interesting but needs a lot more work, so please use the new **Area Suggestion** template to remake it, otherwise I will not be looking into it.
