### ISSUE TITLE
Upgrade center crash

### ISSUE THREAD

**Issue by smackimus** [RicardoTheCoder/ViktorsDiskoveries#14]
# Bug Report

## Describe the bug
When going into upgrades menu it will freeze your game and you will have to close it from taskbar

## To Reproduce

1. Go to 'upgrade station'
2. Click on 'button'
3. See error

## Expected behavior
*I expected it to open the upgrade menu but it crashed my game.*

### Other Mods
e.g. Gold Largos, Science Favorites, etc. (Both from UMF and SRML)*
no other mods
### Game Version
1.4.2
### Mod Version
pre-alpha of Vikdis

## Additional context
impossible to progress because of this

**Comment by DracoClaw** [comment]
Seeing as Science Favorites hasn't worked in a year im closing this bug report. If it still happens when you remove the mod, make a new report.
