### ISSUE TITLE
Garden reset

### ISSUE THREAD

**Issue by GameWorldOfficial** [RicardoTheCoder/ViktorsDiskoveries#17]
# Bug Report

## Describe the bug
*was growing glitch pogo fruit than I fully upgraded the Garden and I had to put in another bug report*

## To Reproduce
*Steps to reproduce the behavior:*

1. Purchase a Garden
2. grow glitch pogo fruit in it
3. fully upgrade it

## Expected behavior
* I expected it to still be growing after the Garden was upgraded*

### Other Mods
umod cheat menu and umod Multi mod*

### Game Version
*1.4.2*

### Mod Version
*Pre-alpha*

## Additional context
*Add any other context about the problem here.*

**Comment by RicardoTheCoder** [comment]
This happens mostly because of the alternative item used to grow the fruit, should not happen again when that is set to normal.
