### ISSUE TITLE
New gadgets + some new lab equipment

### ISSUE THREAD

**Issue by BakarishNotSmart** [RicardoTheCoder/ViktorsDiskoveries#2]
1. Largo separator - A gadget that is fabricated by using a: chicken cloner, 5 manifold cubes and a strange diamond. Basically it looks like a chicken with some small changes. Let's say we have a honey boom largo we want to separate. 
First, we need to put in one of each plorts the largo produces, in our case, we need to put in one honey plort, and one boom plort.
Second, we just shoot the largo trough and it will separate to it's original slimes, in our case a honey and a boom slime.
I can see this being abused to reproduce rare slimes, so I have come up with something to solve it - The separation is a hard process for the separator, so the gears of the machine get stuck after every separation, to get the machine up and running, we have to un-stuck the weels using 2 pieces of primordy oil.

2. targeted extractors- Theese extractors can be set to mine what you want, Each extractor lasts only 2 cycles.
You can't choose to mine anything that's rarer than or is strange diamonds, lava dust and royal jelly.

new lab equipment - Intorucing the, Defabricator! The defabricator is awarded with the last 7zee reward. 
It does exactly what you think. When you have some fabricated gadgets but dont use them, you can youse the defabricator to pay a small fine of 50 NewBucks and get your recources back. 
The recourses will be automaticly put in the refinery.

**Comment by DracoClaw** [comment]
Thank you so much for taking interest in the mod! I highly suggest you read the website before making suggestions. Largo splitting is one of the first things mentioned in Slime Findings - Oh My Tarr. Gadget scrapping/recycling is also planned. If you could please make a new issue for the Targeted Extraction following the format used in my thread I'm sure Ric could find a place for it.
