### ISSUE TITLE
Upgrade menu

### ISSUE THREAD

**Issue by Spinyspino8** [RicardoTheCoder/ViktorsDiskoveries#24]
# Bug Rep

started new game and grabbed 5 pink slimes and put them in a corral, opened the upgrade menu from the upgrade terminal and it froze

1. Start new game

2. Put 5 pink slimes in a corral

3. open the upgrade menu

4. Error

i expected to open the upgrade menu and it wont freeze

**Comment by RicardoTheCoder** [comment]
This does not use the template provided for bug report, a lot of info is missing, please provide the bug report with the right template!

**Comment by GameWorldOfficial** [comment]
This bug has been found already

**Comment by DracoClaw** [comment]
Seeing as you were asked to reformat the report 4 days ago and you did not, I'm assuming the but no longer exists. Feel free to make a new report with the proper format if you still encounter the issue.
