### ISSUE TITLE
Enhanced Tarr Slimes

### ISSUE THREAD

**Issue by TotallyNotAP0LL0** [RicardoTheCoder/ViktorsDiskoveries#3]
**What will this feature do?**
This feature will make Tarr much more dangerous to the player then they used to be, as the Tarr weren't that dangerous. 

- Tarr have the ability to become a black puddle on the ground, the puddle quickly moving to the player along the ground. The Tarr is unable to be damaged during this time as a puddle. The Tarr will pop out the puddle when directly under the player, sending the player upwards and causing damage to them.

- They have the ability to fling nearby Slimes at the Player to cause damage to them, the damage the Slime causes depends on the danger of the Slime that was thrown

- Tarr Slimes have the ability to spew Tar at the player, covering their screen with it, obscuring their vision for a few seconds.

- Some Tarr, on rare occasions, have the ability to consume other Slime Plorts. If they were to consume a Crystal Slime Plort for example, they would gain the ability to make crystals burst out the ground like the Crystal Slimes can. This can also stack with other Plort's up until 3. Eating docile Slime Plorts that wouldn't cause damage to the Player won't do anything. Another example would be a Hunter Plort, which would allow the Tarr Slime to become invisible for a short amount of time.

- Tarr Slime's can also merge with other Tarr Slime's becoming a bit bigger each time. The bigger they get, they more damage they do, but this also makes them weaker and gives the Player a larger area to blast the Tarr with water. (Sorry if its to many features and I should've split them up into comments, I just didn't know if I should since technically its adding onto one feature)

**How it should integrate into the mod? (Optional)**
After Viktor released his vaccine, the Tarr Slimes began to react in unnatural ways a few weeks after the vaccine was released. They seemingly became stronger and more dangerous, along with being more hostile to humans.

**Possible names for the feature? (Optional)**
Danger Tarr's

**Additional context**
Add any other context or screenshots about the feature suggestion here.

**Comment by DracoClaw** [comment]
Again. Like I said on your other post, this is a great idea, but it may be better suited as a small side mod.

**Comment by RicardoTheCoder** [comment]
This does not seem to be something that logic, tarrs could have new behaviors, but I will not be adding things like this. Thank you for the suggestion though.
