### ISSUE TITLE
The ability to make addons

### ISSUE THREAD

**Issue by GameWorldOfficial** [RicardoTheCoder/ViktorsDiskoveries#33]
# Feature Suggestion

**NOTE: If you wish to present more than one feature in this suggestion write each one in a comment**

## What will this feature do?
*using an SDK made by RicTheCoder you will be able to create addons you will be able to make areas and slimes and make a custom title for the addon and control(in chapter: 3) if the slime or area is in the sora continent they can also control everything about the slime like it's behaver or it's environment or it's temp and etc also on the discord a channel where you can share your addons*

## How it should integrate into the mod? (Optional)
*A clear and concise description of how this should integrate with the mod*

## Possible names for the feature? (Optional)
*The VikDisk SDK*

## Reasons for it
*it will make the mod endless unless people stop making addons for the mod. If Ric wants to add a suggestion to VikDisk then he can ask you if you have made an addon for that suggestion if you have then he can integrate the code into VikDisk. It adds creativity to the mod and the mod will be nice to play with addons.*

## Additional context
*the addons will be like mods they will be in the mods folder and can be removed from the mods folder which is how you share them. In the mods tab in-game they will be regarded as mods but next to the title in brackets will say "A VikDisk addon" the "A VikDisk addon" cannot be removed.*

**Comment by DracoClaw** [comment]
I'm closing this because that is literally what the GUU system is about. Plus VikDisk is an open ended mod that promotes collaboration. Your idea is so good that we already took it a year ago. XD

**Comment by GameWorldOfficial** [comment]
OH!
