### ISSUE TITLE
Enhanced Largos

### ISSUE THREAD

**Issue by TotallyNotAP0LL0** [RicardoTheCoder/ViktorsDiskoveries#4]
**What will this feature do?**
This feature will make largos more interesting and perhaps more cosmetically pleasing.

Every Slime will have a color, for example a Pink Slime's color will be Pink. A Boom Slimes color would be red. Each Slime Color will have a specific value assigned to it. The same thing for a Slime's ability, the Boom Slime's ability would be its Explosion.

The Pink Slime's value would be [1,1] and the Boom Slime's ability would also be [2,1]. The Value is composed of two numbers. The first one tells you if its a Ability or not, 1 meaning it isn't and 2 meaning it is. The second dictates the number it uses to correspond the Color with the largo making process.

Their are 2 Values. The Boom Slime has a Color Value and Ability Value. Its Ability Value is [2,1]. Its Color Value is [1,2]. The Pink Slime however has no ability, so it doesn't have an Ability Value and only has its Color Value, which is [1,1] The first digit of a Value tells you if its an Ability or Color Value, 1 meaning its a Color Value and 2 meaning its a Ability Value.

Since the second digit for the Pink Slime's Color Value and the Boom Slime's Ability Value are the same (1), then that means they will both work together when making a largo. This will make the Boom Slime's explosion Pink, since the Pink Slime's specified color is Pink.

Here's an example:

Pink Slime: [1,1] N/A
Boom Slime: [1,2] [2,1]
Crystal Slime: [1,2] [2,2]
Hunter Slime: [1,2] [2,2]

Say you were to make a Hunter Slime and Crystal Slime Largo, it'd work. The Crystal Slime's color would be a brightish blue, and the Hunter Slime's color would be Brown and Black. Since the Hunter Slime's Color Value is [1,2] and the Crystal Slime's Ability Value is [2,2] then that means it'd work. This would make the Crystal Slime's Ability (Creating Crystals) have a Brown and Black color scheme. It'd work the same vice versa since the Hunter Slime's Ability Value and the Crystal Slime's Ability Value is the same.

This'll make it so that a person wouldn't manually have to make every Color Combo, and instead have a script do it for them. This also allows the same to be done with other Slimes fast and easy. (Sorry if its to confusing/complicated or wouldn't work at all, I don't know that much about coding and stuff.)
 
**Possible names for the feature? (Optional)**
Enhanced Largos

**Comment by DracoClaw** [comment]
This is an over complicated way of saying "largo details and effects should match their colors". That being said, I'm all for it. It may be better fit as a separate smaller mod though. But in the end of the day that's up to Ric.

**Comment by RicardoTheCoder** [comment]
Making largos a bit more clever this way can be achieved, but I do agree with @DracoClaw it is an over complicated way of saying you want some improvements on largos. I should look into something similar, and I do intend on it, but it is a bit different from what you are describing.
