### ISSUE TITLE
Deep Water Slime

### ISSUE THREAD

**Issue by Portinari12** [RicardoTheCoder/ViktorsDiskoveries#40]
# New Slime Suggestion

**NOTE: If you wish to present more than one slime in this suggestion write each one in a comment and use the following structure**

## What will this slime look like?
*A clear and concise description of what this slime will look like*

## What kind of slime is it?
* [1 ] **Ranchable Slime** - A slime that can be ranched
* [ ] **Utility Slime** - A slime that provides some functionality to the ranch
* [ ] **Pet Slime** - A slime that can follow you around and do some tasks

## Diet & Favorite Food
*What kind of diet and favority food would this slime have?*

## Plort
*What would be it's plort, does it have any abilities?*
Yeah, it can make a slime swim under water
## Favority Toy
*Does it have a favority toy?*
A octopus plushie
### Type
* [1 ] **Normal** – Just your ordinay slime.
* [ ] **Mutation** – Rare versions of other slimes, like the Albino which is a mutation of the Pink Slime.
* [ ] **Ancient** – Slimes that have lived for a very long time, like the gold slime, it is an ancient being almost as old as the planet
* [ ] **Fossil** – Slimes that can only be found as fossils (or in the case of the saber as descendants). It will be possible to use their DNA, from the fossils, to bring them back.
* [ ] **Godly** – Slimes that have great power and can use some energy similar to magic. They are seen as gods by the other slimes as they keep the slime world alive with their energy.
* [ ] **Special** – Slimes like the Tarr or Twinkle slime are seen as special cause they aren’t normal and don’t fit into any other category.

### Mutation of what slime? (If you choose Mutation above)
*Identify a slime that this is a mutation of, if it is a mutation of something previously suggested, say it is a suggestion given before*

### Behavior
* [ ] **Passive** – Does not damage the rancher in any way. The aggitation will not cause difference in behaviours.
* [1 ] **Neutral** – Might damage the rancher indirectly. The aggitation might cause aggressive behaviour similar to the rolling of the rock slime.
* [ ] **Aggressive** – Attacks the rancher directly.

### Risk for the rancher? (If you choose something other than Passive above)
*What is the risk for the rancher? Directly or Indirectly*
It can stick on players head, than kill him
### Activity Pattern
* [ ] **Diurnal** – Only survives in the light / during the day
* [ ] **Nocturnal** – Only survives in the dark / during the night
* [1] **Metatunal** – Survives in the Dark and Light
* [ ] **Crepuscular** – Is active only during Dusk and Dawn. Disappears during the inactive time.
* [ ] **Matitunal** – Is active only during Dawn. Disappears during the inactive time.
* [ ] **Vespertine** – Is active only during Dusk. Disappears during the inactive time.

### Can become a largo?
* [ ] **Yes** - This slime can become a largo with any slime that normally can.
* [1 ] **Specific** - This slime can only become a largo with specific slimes.
* [ ] **No** - This slime cannot become a largo.

### Largo Specification (If you choose specific above)
*What are the slimes this slime can make largos with?*
Pluddles, rocks, Rad, Crystal, because it lives under water
### Location?
*Either give a specific location or give an idea of places where it could spawn*
You can find it in a new area, and it is like ocean slime, but player dont die when jump in it
### Condition to find?
*If this slime has a condition to find or see it, write it here*
only under water
### Environment?
* [ ] **Any Kind** - Anywhere independent of the type of environment
* [ ] **Land** – Anywhere on land, does not need a special condition for it
* [ ] **Water** – Anywhere on water, does not need a special condition for it
* [1 ] **Deep Water** – On water, requires a place where the water pressure is higher (deep water)
* [ ] **Lava** – On land, requires Lava or a region that contains lava to survive
* [ ] **Arid** – On land, requires a arid/dry zone to survive
* [ ] **Other** - Make a suggestion of a new environment

### Environment Specification (If you choose other above)
*Specify the type of environment and talk a bit about it*

### Temperature
* [ ] **Cold** – Requires cold temperatures (below 15°C/59°F)
* [ ] **Hot** – Requires hot temperatures (above 30°C/86°F)
* [ ] **Moderated** – Requires moderated temperatures (between 10°C/50°F and 35°C/95°F)
* [1 ] **Indifferent** – It doesn’t matter the temperature

### Vaccable?
* [ ] **Yes** - Can be vacced normally
* [1 ] **Upgrade** - Requires an upgrade to be vacced
* [ ] **Conditional** - Can only be vacced under certain conditions
* [ ] **No** - This slime can't be vacced

### Vac Upgrade or Condition (If you choose Upgrade or Conditional above)
*Explain what is the upgrade or condition for this slime to be vacced*
Filter upgrade
## Synergies
*Can this slime synergize with another? If so provide a list of suggestions*

## Possible names for the slime? (Optional)
*If you wish to, please give some names for this slime*
Octopus Slime, Deep water slime, I really dont know
## Additional context
*Add any other context or screenshots about the feature suggestion here.*

**Comment by DracoClaw** [comment]
So you completely ignored two sections. What it looks like and what it eats. The sections you did fill out are neither clear or concise. And you put an 'x' in boxes. Not a '1'. Fix all these and I'll reopen the issue.
