### ISSUE TITLE
more echo's and chime's

### ISSUE THREAD

**Issue by smackimus** [RicardoTheCoder/ViktorsDiskoveries#5]
**What will this feature do?**
This should add more echo's such as a purple echo, this would be purely cosmetic and for fun but its something I think the game doesn't have enough of. I think there should be more chimes since you can't really make much of any songs with only xylophone
so with some guitar notes, you could make rock if you so wished 

**How it should integrate into the mod? (Optional)**
I think they should be found like normal echos and you can catch them like normal echos, and you could add rarer echos with more exclusive colors like black or grey or white. I also think for the chimes part of it that there should be chimes for different instruments like drums instead of just xylophone 

**Possible names for the feature? (Optional)**
More echo's and chime's

**Additional context**
example I made by putting some red and blue echos together that could be a single echo
![433340_screenshots_20200729210530_1](https://user-images.githubusercontent.com/67898148/88876659-029e5880-d1e1-11ea-86a9-d554bb4c76ea.jpg)

**Comment by DracoClaw** [comment]
Pretty sure something like that this is planned with the Carol Slime, and the Wonderland.

**Comment by smackimus** [comment]
ah ok ill close it then

**Comment by smackimus** [comment]
didn't know it was already in the works, so it is closed now
