### ISSUE TITLE
Fur Slime

### ISSUE THREAD

**Issue by DrFlaffer** [RicardoTheCoder/ViktorsDiskoveries#50]
This slime is called fur, because it has ... fur. It will be located in the Frostbite Forest location. His favorite food would be Kookadoba, which I hoped would grow in Frostbite Forest. Plortonomy: The initial plorts rate will be$40. Danger to ranchers: bites.
Description :' Just wants to find friends, but can't'
It will have its own toy: toothy Joe. Description of the toy: 'Fur Slime's only friend'
![i](https://user-images.githubusercontent.com/77445365/104598424-9ed0f480-5687-11eb-9553-8c59fc125e23.jpg)

**Comment by KomiksPL** [comment]
Use the template from "New issue" Slime Suggestion.

**Comment by DracoClaw** [comment]
Follow the formatting please. You can fix this one and I'll reopen the issue.

**Comment by XenonZe** [comment]
lol I love how they never fixed it
