### ISSUE TITLE
Glitch Tarrs from Glitch Plorts.

### ISSUE THREAD

**Issue by MegaPiggy** [RicardoTheCoder/ViktorsDiskoveries#54]
I'm not sure if this is already implemented but I'll suggest it anyways.

## What will this feature do?
Instead of the glitch plorts turning largos into a normal tarr like other plorts do when eaten, it will turn them into glitch tarrs.

**Comment by DracoClaw** [comment]
iirc there are plans to have the "Real Digitarr" be a product of the "Real Glitch Slime" Ric can confirm this.

**Comment by Wooloothedarklord** [comment]
if we have ranchable tarrs then i think this is a great idea.

**Comment by DracoClaw** [comment]
Seeing as this is already planned I'll close this up.
