### ISSUE TITLE
Gliched suggestion

### ISSUE THREAD

**Issue by smackimus** [RicardoTheCoder/ViktorsDiskoveries#6]
**What will this feature do?**
this suggestion is about glitched foods and slimes, my idea is that you can throw any slime in with a bug report and get a glitch slime version of that, such as bug report + tabby slime = glitch tabby slime. now for the foods part, I think you should be able to put in a food and a glitched version of it will come out, like Stoney henhen + bug report = glitched Stoney henhen. I think depending on what it is it glitches in different ways like henhens would be different than pogofruit, I think for rare slimes / slimes that cant turn into largos (like puddle slime since there's no synergy) you could put in some plorts (number depends how rare) and you would get something like a puddle glitch that you would have to put in a pond like normal

**How it should integrate into the mod? (Optional)**
I think that after some experimenting with the glitch slimes in real life he would give you a blueprint for an advanced glitch slime maker that could make more than just normal glitch slimes and glitched pogofruit 

**Possible names for the feature? (Optional)**
GlitHed fOOdS aND slLiMEs

**Additional context**
this could be warped a lot depending on what you want to do with it, could be a whole chapter or just a random side quest

**Comment by RicardoTheCoder** [comment]
This isn't in line with what I want to achieve with my mod, however, one or another thing like a new glitch slime or a new glitch food might be planned in the future.

It will not be anything like what you suggested here though.
