### ISSUE TITLE
Cherry Slime

### ISSUE THREAD

**Issue by wikiwojtek2** [RicardoTheCoder/ViktorsDiskoveries#60]
# New Slime Suggestion

## What will this slime look like?
Looks like cherry

## What kind of slime is it?
* [x] **Pet Slime** - A slime that can follow you around and do some tasks

## Diet & Favorite Food
Diet:Fruit
Fav food:Kookadoba

## Plort
Makes slims happier.can be sold for 82-103

## Favorite Toy
Little Tree

### Type

* [x] **Special** – Slimes like the Tarr or Twinkle slime are seen as special cause they aren’t normal and don’t fit into any other category.

### Behavior
* [x] **Passive** – Does not damage the rancher in any way. The aggitation will not cause difference in behaviours.

### Risk for the rancher? (If you choose something other than Passive above)
They get lost easily

### Activity Pattern

* [x] **Metatunal** – Survives in the Dark and Light

### Can become a largo?
.
* [x] **Specific** - This slime can only become a largo with specific slimes.
*

### Largo Specification (If you choose specific above)
Only with honey slime or another food slime

### Location?
You can find them in seed form in the wilds or on a moss blanket

### Condition to find?
To find a seed you have to look really good. It is very difficult to find

### Environment?

* [x] **Other** - Make a suggestion of a new environment

### Environment Specification (If you choose other above)
to obtain cherry slime you have to plant it in the garden and wait for it to grow

### Temperature

* [x] **Moderated** – Requires moderated temperatures (between 10°C/50°F and 35°C/95°F)

### Vaccable?
* [x] **Yes** - Can be vacced normally

## Synergies
Fruity Largo or  CherryHoney largo

## Additional context
![Cherry_Slime_WIIBOYU](https://user-images.githubusercontent.com/79306451/108525735-b592e880-72d0-11eb-9917-13d8e56b570f.jpg)

**Comment by Wooloothedarklord** [comment]
to be honest, im not a fan of all of these fruit slimes. the strawberry slime was cool but 3 is too many.
