### ISSUE TITLE
Chrono slimes (My take)

### ISSUE THREAD

**Issue by TabbyCreeper** [RicardoTheCoder/ViktorsDiskoveries#63]
# New Slime Suggestion

## What will this slime look like?
Dark blue with clock shape texture in the slime and had a blue arua just like rad slimes

## What kind of slime is it?
* [X] **Ranchable Slime** - A slime that can be ranched
* [ ] **Utility Slime** - A slime that provides some functionality to the ranch
* [ ] **Pet Slime** - A slime that can follow you around and do some tasks

## Diet & Favorite Food
Kookadoba (Past) Pogofruit (Present) Phase Lemons (Future) 

## Plort
it never despawns

## Favorite Toy
Clock

### Type
* [ ] **Normal** – Just your ordinay slime.
* [X] **Mutation** – Rare versions of other slimes, like the Albino which is a mutation of the Pink Slime.
* [ ] **Ancient** – Slimes that have lived for a very long time, like the gold slime, it is an ancient being almost as old as the planet
* [ ] **Fossil** – Slimes that can only be found as fossils (or in the case of the saber as descendants). It will be possible to use their DNA, from the fossils, to bring them back.
* [ ] **Godly** – Slimes that have great power and can use some energy similar to magic. They are seen as gods by the other slimes as they keep the slime world alive with their energy.
* [ ] **Special** – Slimes like the Tarr or Twinkle slime are seen as special cause they aren’t normal and don’t fit into any other category.

### Mutation of what slime? (If you choose Mutation above)
when a quantum slime teleports too far and too fast causing to accidentally time travel

### Behavior
* [X] **Passive** – Does not damage the rancher in any way. The aggitation will not cause difference in behaviours.
* [ ] **Neutral** – Might damage the rancher indirectly. The aggitation might cause aggressive behaviour similar to the rolling of the rock slime.
* [ ] **Aggressive** – Attacks the rancher directly.

### Risk for the rancher? (If you choose something other than Passive above)
ndirect when this slime got agitated their time aura will do a time lapse mode causing it to be fast when you enter it

### Activity Pattern
* [ ] **Diurnal** – Only survives in the light / during the day
* [ ] **Nocturnal** – Only survives in the dark / during the night
* [X] **Metatunal** – Survives in the Dark and Light
* [ ] **Crepuscular** – Is active only during Dusk and Dawn. Disappears during the inactive time.
* [ ] **Matitunal** – Is active only during Dawn. Disappears during the inactive time.
* [ ] **Vespertine** – Is active only during Dusk. Disappears during the inactive time.

### Can become a largo?
* [ ] **Yes** - This slime can become a largo with any slime that normally can.
* [X] **Specific** - This slime can only become a largo with specific slimes.
* [ ] **No** - This slime cannot become a largo.

### Largo Specification (If you choose specific above)
Tabby Slimes, Quantum Slimes, Rad Slimes, Boom Slimes (Possibly Glitch Slimes

### Location?
Everywhere but Rarer than gold slimes (Slightly Common in Ancient Ruins Glass Desert and The wilds)

### Environment?
* [X] **Any Kind** - Anywhere independent of the type of environment
* [ ] **Land** – Anywhere on land, does not need a special condition for it
* [ ] **Water** – Anywhere on water, does not need a special condition for it
* [ ] **Deep Water** – On water, requires a place where the water pressure is higher (deep water)
* [ ] **Lava** – On land, requires Lava or a region that contains lava to survive
* [ ] **Arid** – On land, requires a arid/dry zone to survive
* [ ] **Other** - Make a suggestion of a new environment

### Temperature
* [ ] **Cold** – Requires cold temperatures (below 15°C/59°F)
* [ ] **Hot** – Requires hot temperatures (above 30°C/86°F)
* [ ] **Moderated** – Requires moderated temperatures (between 10°C/50°F and 35°C/95°F)
* [X] **Indifferent** – It doesn’t matter the temperature

### Vaccable?
* [X] **Yes** - Can be vacced normally
* [ ] **Upgrade** - Requires an upgrade to be vacced
* [ ] **Conditional** - Can only be vacced under certain conditions
* [ ] **No** - This slime can't be vacced

## Possible names for the slime? (Optional)
 Time Slime

## Additional context

![Chrono](https://user-images.githubusercontent.com/73280973/109128848-dfde1d80-778a-11eb-8eee-3f8b9cc4b4d3.png)
![Chrono2](https://user-images.githubusercontent.com/73280973/109128852-e2d90e00-778a-11eb-8b4b-564b21cbf6e3.png)

**Comment by TabbyCreeper** [comment]
Oh wait
what?

**Comment by KomiksPL** [comment]
there cannot be any space between [x]

**Comment by TabbyCreeper** [comment]
> there cannot be any space between [x]

Time to edit again

**Comment by DracoClaw** [comment]
Just going to reference #62 and close this one.

**Comment by DracoClaw** [comment]
Just going to reference #62 and close this one.
