### ISSUE TITLE
Infused slimes

### ISSUE THREAD

**Issue by smackimus** [RicardoTheCoder/ViktorsDiskoveries#7]
**What will this feature do?**
I think if the glitch slime maker can infuse a slime with a report of a bug, it might be able to infuse other things too,
imagine infusing a slime and some bread, bread slime? or it could work for already existing slimes like take a rock material then infuse it with a slime, you got a rock slime. this could work for making new slimes not able to be found in the wild and only made or / and it could work to make slimes that already exist, put in a strange diamond, and a slime bang crystal slime. more on the "a slime" thing, I think you could make more special nonwild slimes if you keep combing on a string of infused slimes, an example that would work for non-natural slimes too. ok so let's say you want a crystal slime, you can't just shove a strange diamond and a pink slime in there, you gotta make / find a rock slime and then put the rock slime with the strange diamond. you might think this isn't very useful but if you have just started out and have not gotten the indigo quarry it would be a way to get crystal slimes, this would take a bit of creative thinking for a lot of slimes like a rad slime, you can't put in just pure radioactive energy, so yeah it has a few problems and for abuse like putting in a rock slime and some graviton energy, it could only make a meteor slime if you put in a moon material to upgrade it to take in graviton energy, so you would have to get certain things before you can do that making it more of a quality of life since you don't gotta go all the way to the moon rather than a way of getting rare slimes instantly. as another idea, it could also be used to make normal slime sized largos and slime sized tarr since if you put in 2 slimes then it would make a largo that only has the DNA of both and not the mass. this post is too long to continue for foods so ill go and make a new post

**How it should integrate into the mod? (Optional)**
After getting Viktor more glitch slime plorts 5 days after he would show you his new infuser that can do the job of real glitch slime maker AND infuse slimes

**Possible names for the feature? (Optional)**
Fusions and lab-grown slimes

**Additional context**

**Comment by RicardoTheCoder** [comment]
Other infusions are already possible in the infuser, nothing like you are describing in most cases, there will be no actual fusion of slimes besides making glitch slimes and possibly digi-tarrs. Anything else is planned in a way or another.

Thanks for the suggestion though.
