### ISSUE TITLE
Idea for the new ranchers chapter

### ISSUE THREAD

**Issue by bliksemgiel** [RicardoTheCoder/ViktorsDiskoveries#72]
# Feature Suggestion
 A multiplayer feature

## What will this feature do?
You can play multiplayer with your friends who also love this mod it would be super fun to have multiplayer so you can do the stuff in this mod.

## How it should integrate into the mod? (Optional)
Viktor will do an experiment on the shapeshifter slime and notices that something weird is happening with the plorts when he has the plorts while near a teleported he decides to experiment with the plorts and and he managed to create a way to travel to different universes he decides to go to a other universe and sees its all the same but there are different ranchers they kinda remind him of Beatrix for some reason

## Possible names for the feature? (Optional)
 rangoverse

**Comment by DracoClaw** [comment]
There is already a Multiplayer mod made by Saty. It has a SRML version that supports playing with other mods. Imo the game shouldn't be multiplayer at all, but if you want it I think it's best to leave that to Saty.
