### ISSUE TITLE
Food infusion

### ISSUE THREAD

**Issue by smackimus** [RicardoTheCoder/ViktorsDiskoveries#8]
**NOTE: If you wish to present more than one feature in this suggestion write each one in a comment**

**What will this feature do?**
this is an expansion of the Infused slimes post which is an expansion of my more real glitch slimes idea. this has already been done once with dark ginger, as rick said that dark gingers are infused golden gingers. I think some rare foods can only be made by combining foods with certain things

**How it should integrate into the mod? (Optional)**
The combiner that Viktor gives you after you give him enough glitch plorts if you give the machine every type of food you can find in one place like example: if you give it all the dry reef chickens you can combine all chickens on the dry reef, Stoney henhen + Stoney henhen = Rockey henhen (savannah slime favorite idea? since its an evolved version of henhen just like dark gingers are) but some wouldn't be so obvious 

**Possible names for the feature? (Optional)**
Infused foods

**Additional context**

**Comment by RicardoTheCoder** [comment]
Same answer I gave in the other post, this is already planned, not necessarily the same way you describe but planned either way. 

**Also, when making multiple suggestions, specially when they are related make them in the same post, just add comments with the new suggestion.**
