### ISSUE TITLE
frostbite forest area

### ISSUE THREAD

**Issue by sleepylizard52** [RicardoTheCoder/ViktorsDiskoveries#9]
**NOTE: If you wish to present more than one feature in this suggestion write each one in a comment**

**What will this feature do?**
it will add a new area called the frostbite forest. in the forest there will be frozen fijoas growing on trees. the slimes in this area are called frost slimes and there favorite fruit is the faijoa. the frost slimes ability is it will create snowflakes nearby and when the touch the ground they make a spot of snow. any slime that touches the snow will get frozen for a few seconds. while frozen, slimes dont eat, move, or produce plorts

**How it should integrate into the mod? (Optional)**
this frost area can be on the new continent and adds a new slime and fruit

**Possible names for the feature? (Optional)**
the frostbite forest

**Additional context**
Add any other context or screenshots about the feature suggestion here.

**Comment by smackimus** [comment]
I think it could use a bit more content and a bigger explanation for how it could integrate into the mod

**Comment by DracoClaw** [comment]
I think it's a cute idea, but maybe not the direction of this mod. You are suggesting one slime area and food. Very much the basic fan slime template. The goal of this mod is to have a complete immersion into the story. There are no vanilla biomes with only one food and slime so why here?

**Comment by RicardoTheCoder** [comment]
I suggest you look into the new templates added. You can now use a **Area Suggestion** template to help you out when suggesting a new area. If you still want to suggest this please do so with the new template, otherwise I will not be looking into this suggestion.

**Comment by sleepylizard52** [comment]
ok
